//메뉴
export const menu = [
  {
    id: 1,
    name: "홈",
  },
  {
    id: 2,
    name: "요일별",
    tabMenu: [
      {
        id: 1,
        name: ["월", "mon"],
      },
      {
        id: 2,
        name: ["화", "tue"],
      },
      {
        id: 3,
        name: ["수", "wed"],
      },
      {
        id: 4,
        name: ["목", "thu"],
      },
      {
        id: 5,
        name: ["금", "fri"],
      },
      {
        id: 6,
        name: ["토", "sat"],
      },
      {
        id: 7,
        name: ["일", "sun"],
      },
    ],
  },
  {
    id: 3,
    name: "완결작",
  },
  {
    id: 4,
    name: "베스트도전",
  },
];

//comboBox
export const menuTab = [
  {
    id: 1,
    name: "인기순",
  },
  {
    id: 2,
    name: "여성 인기순",
  },
  {
    id: 3,
    name: "남성 인기순",
  },
  {
    id: 4,
    name: "조회순",
  },
  {
    id: 5,
    name: "업데이트순",
  },
];

export type List = {
  id: number;
  webToon: string;
  name: string;
  favoriteNum: number;
  views: number;
  fViews: number;
  mViews: number;
  day: string[];
  type: string[];
  date: string;
  active: boolean;
};

//신작 리스트
export const newWebToonList = [
  {
    id: 1,
    webToon: "신의탑",
    name: "SIU",
    favoriteNum: 200,
    views: 20000,
    fViews: 8000,
    mViews: 12000,
    day: ["월", "mon"],
    type: ["스토리", "판타지"],
    date: "2021-09-02",
    active: false,
  },
  {
    id: 2,
    webToon: "여신강림",
    name: "야옹이",
    favoriteNum: 100,
    views: 10000,
    fViews: 8000,
    mViews: 2000,
    day: ["화", "tue"],
    type: ["스토리", "로맨스"],
    date: "2021-09-03",
    active: false,
  },
  {
    id: 3,
    webToon: "언덕 위의 제임스",
    name: "쿠당탕",
    favoriteNum: 10,
    views: 5000,
    fViews: 2000,
    mViews: 3000,
    day: ["수", "wed"],
    type: ["에피소드", "개그"],
    date: "2021-09-04",
    active: false,
  },
  {
    id: 4,
    webToon: "하드캐리",
    name: "조양",
    favoriteNum: 15,
    views: 5000,
    fViews: 4000,
    mViews: 1000,
    day: ["목", "thu"],
    type: ["스토리", "드라마"],
    date: "2021-08-05",
    active: false,
  },
  {
    id: 5,
    webToon: "식인귀",
    name: "선택길",
    favoriteNum: 1,
    views: 1000,
    fViews: 400,
    mViews: 600,
    day: ["금", "fri"],
    type: ["스토리", "스릴러"],
    date: "2021-09-06",
    active: false,
  },
  {
    id: 6,
    webToon: "윌유메리미",
    name: "마인드C",
    favoriteNum: 13,
    views: 7000,
    fViews: 5000,
    mViews: 2000,
    day: ["토", "sat"],
    type: ["에피소드", "일상"],
    date: "2021-09-07",
    active: false,
  },
  {
    id: 7,
    webToon: "굿 리스너",
    name: "쥬드프라이데이",
    favoriteNum: 2,
    views: 3000,
    fViews: 2000,
    mViews: 1000,
    day: ["일", "sun"],
    type: ["옴니버스", "드라마"],
    date: "2021-09-08",
    active: false,
  },
  {
    id: 8,
    webToon: "신의탑222",
    name: "SIU222",
    favoriteNum: 30,
    views: 2300,
    fViews: 100,
    mViews: 200,
    day: ["월", "mon"],
    type: ["드라마", "판타지"],
    date: "2021-09-09",
    active: false,
  },
];

//웹툰 리스트
export const webToonList = [
  {
    id: 1,
    webToon: "신의탑",
    name: "SIU",
    favoriteNum: 200,
    views: 20000,
    fViews: 8000,
    mViews: 12000,
    day: ["월", "mon"],
    type: ["스토리", "판타지"],
    date: "2021-08-02",
    active: false,
  },
  {
    id: 2,
    webToon: "여신강림",
    name: "야옹이",
    favoriteNum: 100,
    views: 10000,
    fViews: 8000,
    mViews: 2000,
    day: ["화", "tue"],
    type: ["스토리", "로맨스"],
    date: "2021-08-03",
    active: false,
  },
  {
    id: 3,
    webToon: "언덕 위의 제임스",
    name: "쿠당탕",
    favoriteNum: 10,
    views: 5000,
    fViews: 2000,
    mViews: 3000,
    day: ["수", "wed"],
    type: ["에피소드", "개그"],
    date: "2021-08-04",
    active: false,
  },
  {
    id: 4,
    webToon: "하드캐리",
    name: "조양",
    favoriteNum: 15,
    views: 5000,
    fViews: 4000,
    mViews: 1000,
    day: ["목", "thu"],
    type: ["스토리", "드라마"],
    date: "2021-08-05",
    active: false,
  },
  {
    id: 5,
    webToon: "식인귀",
    name: "선택길",
    favoriteNum: 1,
    views: 1000,
    fViews: 400,
    mViews: 600,
    day: ["금", "fri"],
    type: ["스토리", "스릴러"],
    date: "2021-08-06",
    active: false,
  },
  {
    id: 6,
    webToon: "윌유메리미",
    name: "마인드C",
    favoriteNum: 13,
    views: 7000,
    fViews: 5000,
    mViews: 2000,
    day: ["토", "sat"],
    type: ["에피소드", "일상"],
    date: "2021-08-07",
    active: false,
  },
  {
    id: 7,
    webToon: "굿 리스너",
    name: "쥬드프라이데이",
    favoriteNum: 2,
    views: 3000,
    fViews: 2000,
    mViews: 1000,
    day: ["일", "sun"],
    type: ["옴니버스", "드라마"],
    date: "2021-08-08",
    active: false,
  },
  {
    id: 8,
    webToon: "신의탑222",
    name: "SIU222",
    favoriteNum: 30,
    views: 2300,
    fViews: 100,
    mViews: 200,
    day: ["월", "mon"],
    type: ["드라마", "판타지"],
    date: "2021-08-09",
    active: false,
  },
  {
    id: 9,
    webToon: "여신강림222",
    name: "야옹이222",
    favoriteNum: 20,
    views: 4500,
    fViews: 100,
    mViews: 2000,
    day: ["화", "tue"],
    type: ["판타지", "로맨스"],
    date: "2021-08-04",
    active: false,
  },
  {
    id: 10,
    webToon: "언덕 위의 제임스222",
    name: "쿠당탕222",
    favoriteNum: 9,
    views: 500,
    fViews: 220,
    mViews: 35000,
    day: ["수", "wed"],
    type: ["판타지", "개그"],
    date: "2021-08-01",
    active: false,
  },
  {
    id: 11,
    webToon: "하드캐리222",
    name: "조양2222",
    favoriteNum: 11,
    views: 2035,
    fViews: 125,
    mViews: 250,
    day: ["목", "thu"],
    type: ["개그", "드라마"],
    date: "2021-08-02",
    active: false,
  },
  {
    id: 12,
    webToon: "식인귀222",
    name: "선택길222",
    favoriteNum: 5,
    views: 1201,
    fViews: 214,
    mViews: 111,
    day: ["금", "fri"],
    type: ["드라마", "스릴러"],
    date: "2021-08-09",
    active: false,
  },
  {
    id: 13,
    webToon: "윌유메리미222",
    name: "마인드C222",
    favoriteNum: 5,
    views: 2046,
    fViews: 258,
    mViews: 751,
    day: ["토", "sat"],
    type: ["옴니버스", "일상"],
    date: "2021-08-03",
    active: false,
  },
  {
    id: 14,
    webToon: "윌유메리미222",
    name: "마인드C222",
    favoriteNum: 2,
    views: 2600,
    fViews: 542,
    mViews: 160,
    day: ["일", "sun"],
    type: ["옴니버스", "드라마"],
    date: "2021-08-20",
    active: false,
  },
  {
    id: 15,
    webToon: "신의탑33333",
    name: "SIU3333",
    favoriteNum: 88,
    views: 1234,
    fViews: 233,
    mViews: 425,
    day: ["월", "mon"],
    type: ["옴니버스", "판타지"],
    date: "2021-08-02",
    active: false,
  },
  {
    id: 16,
    webToon: "여신강림3333",
    name: "야옹이3333",
    favoriteNum: 77,
    views: 2063,
    fViews: 369,
    mViews: 741,
    day: ["화", "tue"],
    type: ["스토리", "옴니버스"],
    date: "2021-08-10",
    active: false,
  },
  {
    id: 17,
    webToon: "언덕 위의 제임스3333",
    name: "쿠당탕333",
    favoriteNum: 4,
    views: 2526,
    fViews: 1542,
    mViews: 351,
    day: ["수", "wed"],
    type: ["에피소드", "옴니버스"],
    date: "2021-08-13",
    active: false,
  },
  {
    id: 18,
    webToon: "하드캐리33333",
    name: "조양3333",
    favoriteNum: 2,
    views: 204,
    fViews: 25,
    mViews: 12,
    day: ["목", "thu"],
    type: ["스토리", "에피소드"],
    date: "2021-08-05",
    active: false,
  },
  {
    id: 19,
    webToon: "식인귀33333333",
    name: "선택길3333333",
    favoriteNum: 0,
    views: 201,
    fViews: 222,
    mViews: 22,
    day: ["금", "fri"],
    type: ["스토리", "일상"],
    date: "2021-08-12",
    active: false,
  },
  {
    id: 20,
    webToon: "윌유메리미33333",
    name: "마인드C3333",
    favoriteNum: 11,
    views: 2510,
    fViews: 3621,
    mViews: 521,
    day: ["토", "sat"],
    type: ["에피소드", "스토리"],
    date: "2021-08-13",
    active: false,
  },
  {
    id: 21,
    webToon: "윌유메리미33333",
    name: "마인드C333",
    favoriteNum: 1,
    views: 2154,
    fViews: 32,
    mViews: 1506,
    day: ["일", "sun"],
    type: ["옴니버스", "에피소드"],
    date: "2021-08-17",
    active: false,
  },
  {
    id: 22,
    webToon: "aaaa",
    name: "weee",
    favoriteNum: 25,
    views: 251,
    fViews: 101,
    mViews: 206,
    day: ["월", "mon"],
    type: ["스토리", "판타지"],
    date: "2021-07-23",
    active: false,
  },
  {
    id: 23,
    webToon: "sdsd",
    name: "xvssvs",
    favoriteNum: 21,
    views: 1345,
    fViews: 1545,
    mViews: 215,
    day: ["화", "tue"],
    type: ["판타지", "로맨스"],
    date: "2021-07-14",
    active: false,
  },
  {
    id: 24,
    webToon: "sdwvrrbvb",
    name: "sbettx",
    favoriteNum: 6,
    views: 120500,
    fViews: 20100,
    mViews: 501,
    day: ["수", "wed"],
    type: ["판타지", "개그"],
    date: "2021-07-10",
    active: false,
  },
  {
    id: 25,
    webToon: "xcswe",
    name: "bbdfsw",
    favoriteNum: 3,
    views: 1205,
    fViews: 1055,
    mViews: 30200,
    day: ["목", "thu"],
    type: ["스토리", "개그"],
    date: "2021-07-15",
    active: false,
  },
  {
    id: 26,
    webToon: "cmeri",
    name: "dwkrmwm",
    favoriteNum: 13,
    views: 206200,
    fViews: 100,
    mViews: 360,
    day: ["금", "fri"],
    type: ["에피소드", "스릴러"],
    date: "2021-07-09",
    active: false,
  },
  {
    id: 27,
    webToon: "lxcerk",
    name: "oskirem",
    favoriteNum: 7,
    views: 1025,
    fViews: 151200,
    mViews: 126,
    day: ["토", "sat"],
    type: ["스릴러", "일상"],
    date: "2021-07-07",
    active: false,
  },
  {
    id: 28,
    webToon: "dkw",
    name: "vksdmkfmkmekr",
    favoriteNum: 6,
    views: 125800,
    fViews: 32,
    mViews: 259000,
    day: ["일", "sun"],
    type: ["옴니버스", "드라마"],
    date: "2021-07-18",
    active: false,
  },
];
